<?xml version="1.0"?>
<robot name="two_wheel_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Basic robot structure -->
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_length" value="0.6" />

    <!-- Robot base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} 0.1" />
            </geometry>
            <material>
                <color rgba="0.3 0.3 0.3 1.0" />
            </material>
        </visual>
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material>
                <color rgba="0.8 0.1 0.1 1.0" />
            </material>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 1.5708 0" />
        </visual>
    </link>

    <!-- Right Wheel -->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material>
                <color rgba="0.1 0.1 0.8 1.0" />
            </material>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 1.5708 0" />
        </visual>
    </link>

    <!-- Joints -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="0 ${base_width/2} 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0 -${base_width/2} 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!-- IMU Sensor -->
    <link name="imu_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.01" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
        </inertial>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05" />
            </geometry>
            <material>
                <color rgba="0.0 0.5 0.5 1.0" />
            </material>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>

    <gazebo>
        <plugin name="gazebo_ros_imu" filename="libgazebo_ros_imu.so">
            <ros>
                <namespace>/</namespace>
                <remapping>
                    <imu/ data>/imu/data</imu/data>
                </remapping>
            </ros>
            <imu>
                <topicName>imu/data</topicName>
                <frameName>imu_link</frameName>
                <update_rate>50</update_rate>
            </imu>
        </plugin>
    </gazebo>

</robot>